<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="shredder" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Properties -->
  <xacro:property name="namespace" value="shredder" />
  <xacro:property name="command_topic" value="command/motor_speed" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://rotor_gazebo/meshes/firefly.dae" />
  <xacro:property name="mass" value="3.81" />
  <xacro:property name="body_width" value="0.1" />
  <xacro:property name="body_height" value="0.16" />
  <xacro:property name="mass_rotor" value="0.005" />
  <xacro:property name="arm_length" value="0.3429" />
  <xacro:property name="rotor_offset_top" value="0.06985" />
  <xacro:property name="radius_rotor" value="0.1524" />
  <xacro:property name="motor_constant" value="0.01" />
  <xacro:property name="moment_constant" value="0.0025" />
  <xacro:property name="sin30" value="0.5" />
  <xacro:property name="cos30" value="0.866025403784" />

    <!-- Property Blocks -->
  <xacro:property name="inertia">
    <inertia ixx="0.8244" ixy="0.0" ixz=".1204" iyy="1.135" iyz="0.0" izz="1.759" />
  </xacro:property>

    <xacro:property name="empty_inertia">
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.001" />
  </xacro:property> 

  <xacro:property name="rotor_inertia">
    <xacro:box_inertia x="${radius_rotor}" y="0.015" z="0.003" mass="${mass_rotor*rotor_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Instantiate Links and Joints -->
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <xacro:insert_block name="empty_inertia" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="1 1 1" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
          <box size="${body_width} ${body_width} ${body_height}"/>
        </xacro:unless>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <box size="${body_width} ${body_width} ${body_height}" />
      </geometry>
    </collision>    
  </link>

  <!-- Add Rotors -->
  <xacro:include filename="$(find rotor_gazebo_plugins)/xacro/simple_rotor.xacro"/>
  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="cw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="0"
    color="Red"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>

  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="ccw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="1"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${sin30*arm_length} ${cos30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>

  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="cw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="2"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${sin30*arm_length} ${cos30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>

  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="ccw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="3"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${arm_length} 0 ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>


  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="cw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="4"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="-${sin30*arm_length} -${cos30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>

  <xacro:simple_rotor
    namespace="${namespace}" 
    parent="${namespace}/base_link"
    command_topic="${command_topic}"
    direction="ccw"
    force_constant="${motor_constant}"
    torque_constant="${moment_constant}"
    mass_rotor="${mass_rotor}"
    radius_rotor="${radius_rotor}"
    motor_number="5"
    color="Black"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${sin30*arm_length} -${cos30*arm_length} ${rotor_offset_top}" rpy="0 0 0" />
    <xacro:insert_block name="rotor_inertia" />
  </xacro:simple_rotor>

  <!-- Add IMU -->
    <xacro:include filename="$(find rotor_gazebo_plugins)/xacro/imu.xacro"/>
  <xacro:IMU_ADIS16448 
    namespace="" 
    parent_link="${namespace}/base_link" 
    imu_topic="imu"/>

   <!-- Enable Ground Truth - Used by attitude_controller -->
  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:include filename="$(find rotor_gazebo_plugins)/xacro/odometry_sensor.xacro"/>
    <xacro:ground_truth namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  


</robot>