<?xml version="1.0"?>

<robot name="junker" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="junker"/>
  <xacro:property name="wind_speed_topic" value="gazebo/wind_speed"/>
  <xacro:property name="command_topic" value="/command"/>
  <xacro:property name="use_mesh_file" value="true" />
  <xacro:property name="mesh_file" value="package://fcu_sim/meshes/ju-87.dae"/>
  <xacro:property name="body_width" value="1.4"/>
  <xacro:property name="body_height" value="1.0" />
  <xacro:property name="body_length" value="1.6"/>
  <xacro:property name="mass" value="1.5"/>
  <xacro:property name="Jx" value="0.1147"/>
  <xacro:property name="Jy" value="0.0576"/>
  <xacro:property name="Jz" value="0.1712"/>
  <xacro:property name="Jxz" value="0.0015"/>
  <xacro:property name="rho" value="1.2682"/>
  <xacro:property name="wing_s" value="0.2589"/>
  <xacro:property name="wing_b" value="1.4224"/>
  <xacro:property name="wing_c" value="0.3302"/>
  <xacro:property name="wing_M" value="0.55"/>
  <xacro:property name="wing_epsilon" value="2.8956"/>
  <xacro:property name="wing_alpha0" value="0.18994"/>
  <xacro:property name="k_motor" value="40.0"/>
  <xacro:property name="k_T_P" value="0.0"/>
  <xacro:property name="k_Omega" value="0.0"/>
  <xacro:property name="prop_e" value="0.9"/>
  <xacro:property name="prop_S" value="0.0314"/>
  <xacro:property name="prop_C" value="1.0"/>
  <xacro:property name="C_L_O" value="0.28"/>
  <xacro:property name="C_L_alpha" value="3.45"/>
  <xacro:property name="C_L_beta" value="0.0"/>
  <xacro:property name="C_L_p" value="0.0"/>
  <xacro:property name="C_L_q" value="0.0"/>
  <xacro:property name="C_L_r" value="0.0"/>
  <xacro:property name="C_L_delta_a" value="0.0"/>
  <xacro:property name="C_L_delta_e" value="-0.36"/>
  <xacro:property name="C_L_delta_r" value="0.0"/>
  <xacro:property name="C_D_O" value="0.03"/>
  <xacro:property name="C_D_alpha" value="0.2108"/>
  <xacro:property name="C_D_beta" value="0.0"/>
  <xacro:property name="C_D_p" value="0.0437"/>
  <xacro:property name="C_D_q" value="0.0"/>
  <xacro:property name="C_D_r" value="0.0"/>
  <xacro:property name="C_D_delta_a" value="0.0"/>
  <xacro:property name="C_D_delta_e" value="0.0"/>
  <xacro:property name="C_D_delta_r" value="0.0"/>
  <xacro:property name="C_ell_O" value="0.0"/>
  <xacro:property name="C_ell_alpha" value="0.00"/>
  <xacro:property name="C_ell_beta" value="-0.12"/>
  <xacro:property name="C_ell_p" value="-0.26"/>
  <xacro:property name="C_ell_q" value="0.0"/>
  <xacro:property name="C_ell_r" value="0.14"/>
  <xacro:property name="C_ell_delta_a" value="0.08"/>
  <xacro:property name="C_ell_delta_e" value="0.0"/>
  <xacro:property name="C_ell_delta_r" value="0.105"/>
  <xacro:property name="C_m_O" value="0.0"/>
  <xacro:property name="C_m_alpha" value="-0.38"/>
  <xacro:property name="C_m_beta" value="0.0"/>
  <xacro:property name="C_m_p" value="0.0"/>
  <xacro:property name="C_m_q" value="-3.6"/>
  <xacro:property name="C_m_r" value="0.0"/>
  <xacro:property name="C_m_delta_a" value="0.0"/>
  <xacro:property name="C_m_delta_e" value="-0.5"/>
  <xacro:property name="C_m_delta_r" value="0.0"/>
  <xacro:property name="C_n_O" value="0.0"/>
  <xacro:property name="C_n_alpha" value="0.0"/>
  <xacro:property name="C_n_beta" value="0.25"/>
  <xacro:property name="C_n_p" value="0.022"/>
  <xacro:property name="C_n_q" value="0.0"/>
  <xacro:property name="C_n_r" value="-0.35"/>
  <xacro:property name="C_n_delta_a" value="0.06"/>
  <xacro:property name="C_n_delta_e" value="0.0"/>
  <xacro:property name="C_n_delta_r" value="-0.032"/>
  <xacro:property name="C_Y_O" value="0.0"/>
  <xacro:property name="C_Y_alpha" value="0.00"/>
  <xacro:property name="C_Y_beta" value="-0.98"/>
  <xacro:property name="C_Y_p" value="0.0"/>
  <xacro:property name="C_Y_q" value="0.0"/>
  <xacro:property name="C_Y_r" value="0.0"/>
  <xacro:property name="C_Y_delta_a" value="0.0"/>
  <xacro:property name="C_Y_delta_e" value="0.0"/>
  <xacro:property name="C_Y_delta_r" value="-0.17"/>

  <!-- Property Blocks -->
  <xacro:property name="inertia">
    <inertia ixx="0.8244" ixy="0.0" ixz=".1204" iyy="1.135" iyz="0.0" izz="1.759" />
  </xacro:property>

    <xacro:property name="empty_inertia">
    <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.001" />
  </xacro:property>
    
  <!-- Instantiate Link and Visual -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/wheel.xacro"/>
  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="0 0 0" />
      <xacro:insert_block name="inertia" />
    </inertial>
    <visual name="plane_visual">
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <xacro:if value="${use_mesh_file}">
          <mesh filename="${mesh_file}" scale="0.002 0.002 0.002" />
        </xacro:if>
        <xacro:unless value="${use_mesh_file}">
            <box size="${body_width} ${body_height} ${body_length}" />
        </xacro:unless>
      </geometry>
    </visual>
    <collision name="plane_collision">
      <origin xyz="0 0 0" rpy="1.570796 0 1.570796" />
      <geometry>
        <box size="${body_width} ${body_height} ${body_length}" />
      </geometry>
    </collision>    

    <!-- Wheels -->
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.5} -${body_width*0.5} -${body_height*0.5}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.05">
      <origin xyz="${body_length*0.5} ${body_width*0.5} -${body_height*0.5}"/>
    </xacro:caster>
    <xacro:caster
      radius="0.05">
      <origin xyz="-${body_length*0.5} 0 -${body_height*0.4}"/>
    </xacro:caster>
  </link>


  <!-- Chase Camera -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/camera.xacro"/>
  <xacro:simple_camera
    namespace="${namespace}"
    frame_rate="30"
    rgb_range="1000"
    parent_link="${namespace}/base_link"
    image_topic="chase/rgb"
    image_camera_info_topic="chase/camera_info">
    <origin xyz="-${1.1*body_length} 0 ${0.8*body_height}"/>
  </xacro:simple_camera>

  <!-- Color -->
  <gazebo reference="${namespace}/base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Add Aerodynamics -->
  <gazebo>
    <plugin filename="libfcu_sim_aircraft_forces_and_moments_plugin.so" name="aircraft_forces_and_moments_plugin">
      <namespace>${namespace}</namespace>
      <linkName>${namespace}/base_link</linkName>
      <windSpeedTopic>${wind_speed_topic}</windSpeedTopic>
      <commandTopic>${command_topic}</commandTopic>

      <mass>${mass}</mass>
      <Jx>${Jx}</Jx>
      <Jy>${Jy}</Jy>
      <Jz>${Jz}</Jz>
      <Jxz>${Jxz}</Jxz>
      <rho>${rho}</rho>
      <wing_s>${wing_s}</wing_s>
      <wing_b>${wing_b}</wing_b>
      <wing_c>${wing_c}</wing_c>
      <wing_M>${wing_M}</wing_M>
      <wing_epsilon>${wing_epsilon}</wing_epsilon>
      <wing_alpha0>${wing_alpha0}</wing_alpha0>
      <k_motor>${k_motor}</k_motor>
      <k_T_P>${k_T_P}</k_T_P>
      <k_Omega>${k_Omega}</k_Omega>
      <prop_e>${prop_e}</prop_e>
      <prop_S>${prop_S}</prop_S>
      <prop_C>${prop_C}</prop_C>
      <C_L_O>${C_L_O}</C_L_O>
      <C_L_alpha>${C_L_alpha}</C_L_alpha>
      <C_L_beta>${C_L_beta}</C_L_beta>
      <C_L_p>${C_L_p}</C_L_p>
      <C_L_q>${C_L_q}</C_L_q>
      <C_L_r>${C_L_r}</C_L_r>
      <C_L_delta_a>${C_L_delta_a}</C_L_delta_a>
      <C_L_delta_e>${C_L_delta_e}</C_L_delta_e>
      <C_L_delta_r>${C_L_delta_r}</C_L_delta_r>
      <C_D_O>${C_D_O}</C_D_O>
      <C_D_alpha>${C_D_alpha}</C_D_alpha>
      <C_D_beta>${C_D_beta}</C_D_beta>
      <C_D_p>${C_D_p}</C_D_p>
      <C_D_q>${C_D_q}</C_D_q>
      <C_D_r>${C_D_r}</C_D_r>
      <C_D_delta_a>${C_D_delta_a}</C_D_delta_a>
      <C_D_delta_e>${C_D_delta_e}</C_D_delta_e>
      <C_D_delta_r>${C_D_delta_r}</C_D_delta_r>
      <C_ell_O>${C_ell_O}</C_ell_O>
      <C_ell_alpha>${C_ell_alpha}</C_ell_alpha>
      <C_ell_beta>${C_ell_beta}</C_ell_beta>
      <C_ell_p>${C_ell_p}</C_ell_p>
      <C_ell_q>${C_ell_q}</C_ell_q>
      <C_ell_r>${C_ell_r}</C_ell_r>
      <C_ell_delta_a>${C_ell_delta_a}</C_ell_delta_a>
      <C_ell_delta_e>${C_ell_delta_e}</C_ell_delta_e>
      <C_ell_delta_r>${C_ell_delta_r}</C_ell_delta_r>
      <C_m_O>${C_m_O}</C_m_O>
      <C_m_alpha>${C_m_alpha}</C_m_alpha>
      <C_m_beta>${C_m_beta}</C_m_beta>
      <C_m_p>${C_m_p}</C_m_p>
      <C_m_q>${C_m_q}</C_m_q>
      <C_m_r>${C_m_r}</C_m_r>
      <C_m_delta_a>${C_m_delta_a}</C_m_delta_a>
      <C_m_delta_e>${C_m_delta_e}</C_m_delta_e>
      <C_m_delta_r>${C_m_delta_r}</C_m_delta_r>
      <C_n_O>${C_n_O}</C_n_O>
      <C_n_alpha>${C_n_alpha}</C_n_alpha>
      <C_n_beta>${C_n_beta}</C_n_beta>
      <C_n_p>${C_n_p}</C_n_p>
      <C_n_q>${C_n_q}</C_n_q>
      <C_n_r>${C_n_r}</C_n_r>
      <C_n_delta_a>${C_n_delta_a}</C_n_delta_a>
      <C_n_delta_e>${C_n_delta_e}</C_n_delta_e>
      <C_n_delta_r>${C_n_delta_r}</C_n_delta_r>
      <C_Y_O>${C_Y_O}</C_Y_O>
      <C_Y_alpha>${C_Y_alpha}</C_Y_alpha>
      <C_Y_beta>${C_Y_beta}</C_Y_beta>
      <C_Y_p>${C_Y_p}</C_Y_p>
      <C_Y_q>${C_Y_q}</C_Y_q>
      <C_Y_r>${C_Y_r}</C_Y_r>
      <C_Y_delta_a>${C_Y_delta_a}</C_Y_delta_a>
      <C_Y_delta_e>${C_Y_delta_e}</C_Y_delta_e>
      <C_Y_delta_r>${C_Y_delta_r}</C_Y_delta_r>
    </plugin> 
  </gazebo>

  <!-- Sensors -->
  <gazebo>
    <plugin filename="libfcu_sim_aircraft_truth_plugin.so" name="aircraft_truth_plugin">
      <namespace>${namespace}</namespace>
      <linkName>${namespace}/base_link</linkName>
      <windSpeedTopic>${wind_speed_topic}</windSpeedTopic>
    </plugin>
  </gazebo>

  <!-- Airspeed -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/airspeed.xacro"/>
  <xacro:airspeed_MPXV5004G
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    airspeed_topic="airspeed/data">
  </xacro:airspeed_MPXV5004G>

  <!-- GPS -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/GPS.xacro"/>
  <xacro:GPS_BYU
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    GPS_topic="gps/data">
  </xacro:GPS_BYU>

  <!-- Sonar and Barometer -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/altimeter.xacro"/>
  <xacro:Sonar_HC-SR04
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    altimeter_topic="sonar/data">
  </xacro:Sonar_HC-SR04>
  <xacro:Barometer_MS5611
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    altimeter_topic="baro/data">
  </xacro:Barometer_MS5611>

  <!-- IMU -->
  <xacro:include filename="$(find fcu_sim_plugins)/xacro/imu.xacro"/>
  <xacro:IMU_MPU6050
    namespace="${namespace}"
    parent_link="${namespace}/base_link"
    imu_topic="imu/data">
  </xacro:IMU_MPU6050>

</robot>
